FROM python:3.11-slim-buster

RUN apt-get update && \
    apt-get install -y \
    git \
    # dependencies for opencv
    libgl1-mesa-glx \
    libglib2.0-0

RUN apt-get clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY backend/requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY backend /app/
CMD ["python", "main.py"]
